### ISSUE TITLE
Refactor Bug List

### ISSUE THREAD

**Issue by Vorlias** [roblox-ts/roblox-ts#1055]
I'm going to keep this updated with any issues (as replies) I find relating to the new compiler while I move my game across.

----
## Static Field Emit
```lua
    function ZStats.new(...)
        local self = setmetatable({}, ZStats)
        self:constructor(...)
        return self
    end
    ZStats.ZERO = ZStats.new({}, 0)
    ZStats.BASE = ZStats.new({}, 1)
    function ZStats:constructor(stats, defaultStatAmount)
        if defaultStatAmount == nil then defaultStatAmount = 0 end
        self.mStrength = ((stats.Strength ~= nil) and stats.Strength or defaultStatAmount);
        self.mEndurance = ((stats.Endurance ~= nil) and stats.Endurance or defaultStatAmount);
        self.mIntellect = ((stats.Intellect ~= nil) and stats.Intellect or defaultStatAmount);
        self.mSpirit = ((stats.Spirit ~= nil) and stats.Spirit or defaultStatAmount);
        self.mAgility = ((stats.Agility ~= nil) and stats.Agility or defaultStatAmount);
        self.mCriticalStrike = ((stats.CriticalStrike ~= nil) and stats.CriticalStrike or defaultStatAmount)
    end
```
Static fields should be _after_ `constructor`, as in this instance - constructor isn't defined and Lua throws an error due to this.

----

This can be worked around by moving the static fields below the constructor, but it _should_ always have the constructor first regardless.

----
# Bug List
### Functions
- [x] [Hoisting of async functions incorrect when it calls itself](https://github.com/roblox-ts/roblox-ts/issues/1055#issuecomment-657001760)
### Classes
- [x] Static Field Emit
### Objects
- [x] [Spread on undefined value](https://github.com/roblox-ts/roblox-ts/issues/1055#issuecomment-649913549)
### Indexing
- [x] [Alias for Roact.Children in object destructuring results in invalid offset addition to Roact.Children.](https://github.com/roblox-ts/roblox-ts/issues/1055#issuecomment-649916084)
### Macros
- [x] [Return value for Push incorrect](https://github.com/roblox-ts/roblox-ts/issues/1055#issuecomment-649992192)
- [ ] [Array splice doesn't work](https://github.com/roblox-ts/roblox-ts/issues/1055#issuecomment-653836392)
- [x] [Use of string.includes emits invalid code](https://github.com/roblox-ts/roblox-ts/issues/1055#issuecomment-653840003)

**Comment by Dionysusnu** [comment]
Shall we make this a mono-issue for all refactor bugs?

**Comment by Vorlias** [comment]
https://osyrisrblx.github.io/playground/#code/JYWwDg9gTgLgBAJQgQwMbwGZQiOAiAASgCMAPGAZwHps0Y8BuAKCYwFcA7dYCDuGAKYUYACjDYwFAPwAuOAAVksYMgA2AHgBiUZCAEA+AJRwA3kzgW4UATDZQ+6rLoGmAdO-ERJAXyr6m3kA

- [ ] Spread on undefined value

```ts
import Roact from "@rbxts/roact";

function test(props?: Partial<Frame>) {
    return <frame {...props}/>
}
```
Results in 
```lua
local function test(props)
	local _0 = {}
	for _1, _2 in pairs(props) do
		_0[_1] = _2
	end
	return Roact.createElement("Frame", _0)
end
```

`props` in this case _could_ be `nil`, thus Lua errors due to not being able to use pairs on `nil`. This applies to regular object spreads as well. This is valid in JS/TypeScript.

**Comment by Vorlias** [comment]
- [ ] Alias for `Roact.Children` in object destructuring results in invalid indexing

https://osyrisrblx.github.io/playground/#code/JYWwDg9gTgLgBAJQgQwMbwGZQiOAiAASgCMAPGAZwHps0Y8BuAKCYFNTJY4ATVjZAK4AbeKiHIKFOAFkAngGEckAHatl8djDXcpSOgDpF4CKvVwA3kzjW4YAcSHBUcKNtZQAFAEoLVm-9QTCnhzAG09dEMAC2AhbldlAF0ALjhUGLiEgF84AF44GBiKfTBsMApmf39XGAEoZTgAHixkEFYAPj8qqvN02Pi1LK6qxqoWtvbKmyGsoA

```ts
import Roact from "@rbxts/roact";

export default class MyComponent extends Roact.Component {
    public render() {
        const {[Roact.Children]: children} = this.props;
        return <frame>
            {children}
        </frame>;
    }
}
```

`children` ends up being
```lua
local children = _0[Roact.Children + 1]
```

when it should be
```lua
local children = _0[Roact.Children]
```

**Comment by Vorlias** [comment]
- [ ] Return value of push is incorrect

https://osyrisrblx.github.io/playground/#code/MYewdgzgLgBFCm0CCAnFBDAnjAvDA2gEQAS8ANmSIQLoDcAUPaJLAJYAmAHrnIlKhkwA6AA4BXCAAsAFIUms4k+CniEAlAxEpWYKNI6cNQA

```ts
const testArray = ["Hello"];

const idx = testArray.push("hi there");
print(idx);
```
The expected output should be `2`, as it's the second element. `3` is given instead.

Incorrect emit:
```lua
-- Compiled with roblox-ts v0.4.0
local testArray = { "Hello" }
-- ▼ Array.push ▼
testArray[#testArray + 1] = "hi there"
-- ▲ Array.push ▲
local idx = #testArray + 1
print(idx)
```
Corrected emit:
```lua
-- Compiled with roblox-ts v0.4.0
local testArray = { "Hello" }
-- ▼ Array.push ▼
testArray[#testArray + 1] = "hi there"
-- ▲ Array.push ▲
local idx = #testArray
print(idx)
```

**Comment by brianush1** [comment]
# Array splice doesn't work

https://osyrisrblx.github.io/playground/#code/MYewdgzgLgBAhgJwTAvDA2gRgDQwEy4DMAugNwBQiCAdBAA4A2AlsAKYAUADLpgJQVA

```ts
const arr = [1, 2, 3];
arr.splice(0, 1);

```

The code generated for this segment is erroneous:

```lua
-- Compiled with roblox-ts v0.4.0
local arr = { 1, 2, 3 }
arr:splice(0, 1)
return nil

```

**Comment by brianush1** [comment]
# Use of string.includes emits invalid code

https://osyrisrblx.github.io/playground/#code/A4JwlgdgLgFARAQwM4BM4DpIGMA2BXFAUyXiTgEpyBuAKCA

```ts
print("asd".includes("s"));
```

The code generated for this segment is erroneous:

```lua
-- Compiled with roblox-ts v0.4.0
print(("asd"):includes("s"))
return nil

```

**Comment by osyrisrblx** [comment]
# Roact JSX "Key" only works with ts.StringLiteral

https://osyrisrblx.github.io/playground/#code/JYWwDg9gTgLgBAJQgQwMbwGZQiOAiAASgCMAPGAZwHps0Y8BuAKFQgDsL5k4BeOAHizIQAUzgBpEQE8eeALJSAYlGEi8APn5Uho9c1Yd4xXgJ1jJMgN7ylK0XgC+m7XZF6mQA

```TS
import Roact from "@rbxts/roact";
const a = <frame Key="MyFrame"></frame>;
const b = <frame Key={"MyFrame"}></frame>;
```

```Lua
-- Compiled with roblox-ts v0.4.0
local TS = _G[script]
local Roact = TS.import(script, TS.getModule(script, "roact"))
local a = Roact.createFragment({
	MyFrame = Roact.createElement("Frame"),
})
local b = Roact.createElement("Frame")
return nil
```

**Comment by Vorlias** [comment]
# Hoisting of async functions incorrect when it calls itself

https://osyrisrblx.github.io/playground/#code/IYZwngdgxgBAZgV2gFwJYHsLyVNmAqAFsMgMLAA2FIAksiAKYVwAUAlDAN4BQMf2KDBCIlyVWvSas2Abm4BfIA
