### ISSUE TITLE
Release Plan

### ISSUE THREAD

**Issue by osyrisrblx** [roblox-ts/roblox-ts#1654]
- [ ] Update [CHANGELOG.md](https://github.com/roblox-ts/roblox-ts/blob/master/CHANGELOG.md)
- [ ] Bump version number in `package.json` and run `npm install` to update `package-lock.json`
- [ ] `npm test` to ensure tests pass locally, latest CI on master should be green as well
- [ ] `npm publish`
- [ ] `@rbxts/compiler-types`
  - [ ] Bump version and run `npm publish`
  - [ ] `./update-compiler-tag.sh`
- [ ] Create GitHub release
- [ ] Post announcement on Discord
- [ ] [Run playground deploy workflow](https://github.com/roblox-ts/roblox-ts.com/actions/workflows/main.yml)
