### ISSUE TITLE
Goals

### ISSUE THREAD

**Issue by osyrisrblx** [roblox-ts/roblox-ts#358]
- [x] Resolve runtime library location better #406 
- [x] Support plugin development #409  (+ types)
- [x] Rework Project.ts
- [x] Support Rojo 0.5 #403 
- [ ] Finish #436 
- [x] Rework Classes #163 
- [x] Investigate Decorators #140 
- [ ] Make instanceof use Symbol.hasInstance internally #135
- [x] For..of loop should use Symbol.iterator internally #131

**Comment by Validark** [comment]
For Project.ts, consider this change contributed by @grubsteak https://github.com/roblox-ts/roblox-ts/pull/344/files#diff-a1825f8749cecf5d931277a23a9e7c14L349

**Comment by grubsteak** [comment]
My change doesn't work with index files named `index.client.ts`, `index.client.tsx`, `index.server.ts`, or 'index.server.tsx'

**Comment by Validark** [comment]
My to-do list:
* [ ] Rewrite and fix the ObjectLiteral compilation code, including https://github.com/roblox-ts/roblox-ts/issues/351
* [ ] Fix https://github.com/roblox-ts/roblox-ts/issues/360
* [ ] Fix https://github.com/roblox-ts/roblox-ts/issues/354 if possible
* [ ] Implement https://github.com/roblox-ts/roblox-ts/issues/404
* [ ] Split up call.ts
* [ ] Disallow LuaTuples in conditionals https://github.com/roblox-ts/roblox-ts/issues/349
